### PR TITLE
doc: new ability: metrics

### PR DESCRIPTION
**Pull request by jiang1997**
https://github.com/apache/skywalking-python/pull/231

Thank @Superskyyy for reminding me. 
refers to https://github.com/apache/skywalking-java/tree/main/docs

### CODE REVIEW

**Review by Superskyyy — APPROVED** [review]

**Comment by Superskyyy** [comment]
@jiang1997 website repo will also need an update.

**Comment by wu-sheng** [comment]
From my reading of #238, we wouldn't providr general meter/metrics APIs, right?
Adding metrics capacity to the agent seems misguided.

**Comment by wu-sheng** [comment]
PVM metrics collecting is different with meter collecting in general understanding.

**Comment by kezhenxu94** [comment]
> From my reading of #238, we wouldn't providr general meter/metrics APIs, right?
> Adding metrics capacity to the agent seems misguided.

Read this https://github.com/apache/skywalking-python/pull/231

**Comment by kezhenxu94** [comment]
> PVM metrics collecting is different with meter collecting in general understanding.

Collecting PVM metrics is based on the general-purpose API.

**Comment by wu-sheng** [comment]
Thanks for the update.

**Comment by jiang1997** [comment]
> @jiang1997 website repo will also need an update.

Got it.

**Pull request merged**
