### PR TITLE
Add thread propagation

### PR DESCRIPTION
**Pull request by alonelaval**
resolve apache/skywalking#5257

### CODE REVIEW

**Comment by alonelaval** [comment]
> Could you please add the new decorator to the doc, it'c a cool feature that the users should learn it from the doc

OK

**Comment by shuguang-dong** [comment]
hello，I have a trouble when use skywalking-python:
I learn skywalking-python by this page: https://github.com/apache/skywalking-python
after agent.start(),only create instance,but not track any request,
can you help me? 
my email is dongshuguang_1993@163.com
and QQ is  709936344
thanks!

**Comment by kezhenxu94** [comment]
> hello，I have a trouble when use skywalking-python:
> 
> I learn skywalking-python by this page: https://github.com/apache/skywalking-python
> 
> after agent.start(),only create instance,but not track any request,
> 
> can you help me? 
> 
> my email is dongshuguang_1993@163.com
> 
> and QQ is  709936344
> 
> thanks!

What framework are you using, make sure the framework is supported in the list and there is traffic actually

**Comment by kezhenxu94** [comment]
@shuguang-dong also, please open an individual issue in the main repo because your question is not related to this pull request, it confuses others in this thread

**Pull request merged**
