### PR TITLE
Feature: adapt HTTP protocol

### PR DESCRIPTION
**Pull request by kezhenxu94**
may need some performance tuning later

### CODE REVIEW

**Comment by kezhenxu94** [comment]
> No object about this feature, but the question is why? Who will need this? As clearly, gRPC provides much better performance, and the backend prefers the gRPC too.

If the user has already used gRPC in their application, and the version is incomparable with the one we are using, this would help, because there is no shaded packages in python and versions in python are somewhat sensitive

**Comment by wu-sheng** [comment]
OK, get your point, but we should indicate in the document, `gRPC` is recommended. Even we don't have the comparison data, gRPC is better than HTTP, agree?

**Comment by kezhenxu94** [comment]
> OK, get your point, but we should indicate in the document, `gRPC` is recommended. Even we don't have the comparison data, gRPC is better than HTTP, agree?

Sure, will add it later

**Comment by wu-sheng** [comment]
Recommend add HTTP test into main repo e2e too, should be an easy work :)

**Pull request merged**
