### PR TITLE
make @trace decorator support async functions

### PR DESCRIPTION
**Pull request by taskmgr**
Closes https://github.com/apache/skywalking/issues/5770

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Please always use English in GitHub issues and mailing list

**Review by kezhenxu94 — COMMENTED** [review]
You should define 2 wrapper functions, one for ordinary(the original version) and one for async,

**Comment by taskmgr** [comment]
> 
> 
> You should define 2 wrapper functions, one for ordinary(the original version) and one for async,

I've committed a new version.

**Comment by kezhenxu94** [comment]
@taskmgr tests passed, please consider refactor the two functions to extract the common codes

**Review by kezhenxu94 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
