### PR TITLE
Enable E2E batch mode and pin Infra-E2E version

### PR DESCRIPTION
**Pull request by Superskyyy**
Batch E2E outputs to avoid excessive log.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes: <URL to main repo issue>
- [ ] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by Superskyyy** [comment]
This PR is no longer needed right? Since it's enabled by default now.

**Comment by wu-sheng** [comment]
Do the project lock the version?

**Comment by kezhenxu94** [comment]
> This PR is no longer needed right? Since it's enabled by default now.

Yes, but I suggest we should pin the github action to a specific revision/commit

**Comment by Superskyyy** [comment]
Ok let me lock it (was previously curious to see if we could spot e2e bugs by applying @main here )

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
