### PR TITLE
Add hbase happy plugin

### PR DESCRIPTION
**Pull request by alidisi**
### <Feature description>

- [x] I have added the library to `pyproject.toml` (plugin group) by running `poetry add library --group plugins`
- [X] I have rebuilt the `Plugins.md` documentation by running `make doc-gen`
- [X] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please git rebase your commits.

**Comment by wu-sheng** [comment]
Have the component ID and icon been added? You clicked the checkbox, but I never saw the relative PR.

**Comment by alidisi** [comment]
> Have the component ID and icon been added? You clicked the checkbox, but I never saw the relative PR.

maybe ,I understand the mistake. I just add component ID in  skywalking/__init__.py  and  see the icon has been added , not submit PR alone

**Comment by wu-sheng** [comment]
You need to submit pull requests to the main repo and UI to add component ID and icon.

**Comment by wu-sheng** [comment]
- Component ID PR ref, https://github.com/apache/skywalking/pull/10078
- Icon PR ref, https://github.com/apache/skywalking-booster-ui/pull/201

To verify it works, you should change both locally, and use your plugin to monitor a service. If all things work, you should be able to see the component name and icon on the topology on the UI.

**Comment by alidisi** [comment]
> * Component ID PR ref, [Add Micrometer as a component skywalking#10078](https://github.com/apache/skywalking/pull/10078)
> * Icon PR ref, [Added Micrometer icon skywalking-booster-ui#201](https://github.com/apache/skywalking-booster-ui/pull/201)
> 
> To verify it works, you should change both locally, and use your plugin to monitor a service. If all things work, you should be able to see the component name and icon on the topology on the UI.

I have change the Component ID to eixted Component , and it can see the right icon on my local oap server Topology. Should   
i close the PR and summit a new PR ?

**Comment by wu-sheng** [comment]
You don't need to close and open, learn git, git rebase could fix this.

**Comment by wu-sheng** [comment]
https://github.com/apache/skywalking/blob/fba96452f59a2e04d072c97592797c04e7fa6481/oap-server/server-starter/src/main/resources/component-libraries.yml#L331

Please update language in the YAML.

**Comment by Superskyyy** [comment]
Now the remaining thing is to wait on your PR for the Main repo to add component ID (remember to add Python to YAML) and LOGO to UI repo then we are all set!

**Comment by alidisi** [comment]
> Now the remaining thing is to wait on your PR for the Main repo to add Python to YAML [here](https://github.com/apache/skywalking/blob/fba96452f59a2e04d072c97592797c04e7fa6481/oap-server/server-starter/src/main/resources/component-libraries.yml#L331) then we are all set!

I submit the PR #10272 to  update component-libraries.yml HBase languages python

**Pull request merged**
