### PR TITLE
removed requests as required dependency

### PR DESCRIPTION
**Pull request by tom-pytel**
Fix https://github.com/apache/skywalking/issues/7282 due to #125

### CODE REVIEW

**Comment by tom-pytel** [comment]
So if you have nothing against it I will look into replacing requests with standard python lib urllib to do the connections?

**Review by wu-sheng — APPROVED** [review]
Do we need

**Comment by wu-sheng** [comment]
FYI @potiuk This has been reverted and kept optional only.

**Comment by tom-pytel** [comment]
> Do we need

A different communication method? If requests is license problematic then why not change to standard python lib if possible, one less dependency too.

**Comment by wu-sheng** [comment]
> > Do we need
> 
> A different communication method? If requests is license problematic then why not change to standard python lib if possible, one less dependency too. https://github.com/psf/requests/pull/5797. We just need their new release.

Sorry, it was a copy/paste issue. There is no issue. This dependency issue should be resolved from the upstream repo already.

**Comment by tom-pytel** [comment]
Heads up, I just grabbed the latest master which should have this and #127 merged and this change is not present. `setup.py` still contains `requests` as a required dependency. Guessing merge with @127 list it?

**Comment by kezhenxu94** [comment]
> Heads up, I just grabbed the latest master which should have this and #127 merged and this change is not present. `setup.py` still contains `requests` as a required dependency. Guessing merge with @127 list it?

Hey, I can see `requests` is not required dependency. https://github.com/apache/skywalking-python/blob/master/setup.py It’s in `http` extra dependency.

**Comment by potiuk** [comment]
Correct. I mentioned that in my report. So this is right, it's not *necesssary* according to the ASF Policy (similarly in Airflow we have a lot of extras with `requests`) - the "optional" LGPL dependency is acceptable. But once the new version is out, I think it would be great to make it "minimal" version of requests - this way the LGPL dependency becomes optional even for optional dependencies ;)

**Pull request merged**
