### PR TITLE
Test: set up plugin tests and add http plugin test

### PR DESCRIPTION
**Pull request by kezhenxu94**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Tests fail.

**Comment by kezhenxu94** [comment]
Passed

**Comment by kezhenxu94** [comment]
Merging

**Comment by wu-sheng** [comment]
I think this repo is not set review required yet. @kezhenxu94

**Comment by kezhenxu94** [comment]
Jira ticket had been created, hope we get some reviewers in the repo

**Comment by alonelaval** [comment]
sorry，I'm just logging in now

**Pull request merged**
