### PR TITLE
Fix sw8 loss when use aiohttp.

### PR DESCRIPTION
**Pull request by Forstwith**
Fix sw8 loss when use aiohttp.
In /plugins/sw_aiohttp.py
When headers is not MultiDictProxy or MultiDict , headers = CIMultiDict(headers) make the headers not the same object as kwargs['headers'] . Therefore, the carrier information is not added to the actual sent headers
```python
if headers is None:
    headers = kwargs['headers'] = CIMultiDict()
elif not isinstance(headers, (MultiDictProxy, MultiDict)):
    headers = CIMultiDict(headers)
    kwargs['headers'] = headers     # add this line to add headers back.
for item in carrier:
    headers.add(item.key, item.val)
```

### Fix <bug description or bug issue link>
- [ ] Add a unit test to verify that the fix works.
- [x] Explain briefly why the bug exists and how to fix it.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes:[ [<URL to main repo issue>](https://github.com/apache/skywalking/issues/10669)](https://github.com/apache/skywalking/issues/10669)
- [x] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
You at least missed to update change log file.
Please read PR template.

**Comment by wu-sheng** [comment]
Why close?

**Comment by Forstwith** [comment]
> Why close?
I want to add a changelog, and then reopen

**Comment by wu-sheng** [comment]
You don't need to close/reopen, just update on your branch.

**Comment by Forstwith** [comment]
Yes, thanks for letting me know that I don't have to close/reopen. I've added the changelog, and reopened.

**Comment by Superskyyy** [comment]
Hello，you should move the changelog to 1.1.0 as 1.0.0 was already released.

**Comment by Forstwith** [comment]
> Hello，you should move the changelog to 1.1.0 as 1.0.0 was already released.

I saw that @wu-sheng has updated it for me, many thanks. I see that one of the unit tests is failing, is there anything I can do?

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
