### PR TITLE
loose restrict of greenlet (#3)

### PR DESCRIPTION
**Pull request by jaychoww**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes: <URL to main repo issue>
- [ ] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).
- [ ] The latest gevent version (>=22.10.2) has resolved the compatibility issue with greenlet (>=2.0.0). Greenlet (1.1.3) works  incorrectly when utilized with Python 3.7 and higher (Python 3.7+ should also employ gevent>=22.10). As a result, we should eliminate the limitation on the greenlet version (<=1.1.3).

### CODE REVIEW

**Comment by Superskyyy** [comment]
Thanks! Can you check this comment and confirm the error you encountered in the psutil package? https://github.com/apache/skywalking/issues/11481

**Comment by jaychoww** [comment]
> @jaychoww Thanks! Can you check this comment and confirm the error you encountered in the psutil package? [apache/skywalking#11481](https://github.com/apache/skywalking/issues/11481)

yes, I temperately restrict the psutil<=5.9.5 for this issue.

**Comment by Superskyyy** [comment]
Ok, let's merge this first, few related issues seem to be reported to psutil too, I will continue to monitor that and loosen the version requirements once fixed.

**Comment by Superskyyy** [comment]
Thanks for the PR! @jaychoww

**Review by Superskyyy — APPROVED** [review]

**Pull request merged**
