### PR TITLE
Remove docs from main README.md - Add website doc links.

### PR DESCRIPTION
**Pull request by Superskyyy**
- Remove docs from main README.md 

- Add website doc links.

Waiting on https://github.com/apache/skywalking-website/pull/330

Closes https://github.com/apache/skywalking/issues/7687

Signed-off-by: Superskyyy <Superskyyy@outlook.com>

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]

**Comment by kezhenxu94** [comment]
FYI @Superskyyy python 3.5 is EOL and we failed to build the Docker images for it, maybe we can consider removing it from our Makefile

**Comment by Superskyyy** [comment]
> FYI @Superskyyy python 3.5 is EOL and we failed to build the Docker images for it, maybe we can consider removing it from our Makefile

I can see there are py3.5 kafka and grpc images in Docker Hub, the http one is missing, did it fail to build? I thought that just leads to a warning during the pull.

Python 3.10.0 final will come out on Monday, 2021-10-04, scheduled to release.

When that releases, I think probably remove it totally from the setup.py and move our support versions up to 3.10.

**Comment by kezhenxu94** [comment]
@Superskyyy py3.5 failed to build b/c it failed to install `requests==2.26`, I think `requests` just dropped supporting py3.5 right before 2.26 😂

**Comment by Superskyyy** [comment]
> @Superskyyy py3.5 failed to build b/c it failed to install `requests==2.26`, I think `requests` just dropped supporting py3.5 right before 2.26 😂

o.O💧 Our requirements.txt shows requests == 2.24 though, my local build passed.

**Comment by wu-sheng** [comment]
Another reminder, this docker hub repo is missing on the website, https://skywalking.apache.org/downloads/#docker-images-for-convenience. Please fix.

**Comment by kezhenxu94** [comment]
when building the official docker images, it downloads the agent via `pip` and the `requests` version in `setup.py` takes effect, maybe you tested locally with `requests==2.24` already installed, your tests passed indeed. Maybe installing `requests==2.25` first and then install `skywalking==0.7.0` in the Dockerfile do the trick 😉 but I'd rather drop support for py 3.5 directly as it's EOL

**Comment by Superskyyy** [comment]
> when building the official docker images, it downloads the agent via `pip` and the `requests` version in `setup.py` takes effect, maybe you tested locally with `requests==2.24` already installed, your tests passed indeed. Maybe installing `requests==2.25` first and then install `skywalking==0.7.0` in the Dockerfile do the trick 😉 but I'd rather drop support for py 3.5 directly as it's EOL

Ah I see, that part I missed. Sure drop it.

**Comment by Superskyyy** [comment]
> Another reminder, this docker hub repo is missing on the website, https://skywalking.apache.org/downloads/#docker-images-for-convenience. Please fix.

Will add that in a minute.

**Pull request merged**
