### PR TITLE
Add namespace suffix to service name

### PR DESCRIPTION
**Pull request by SheltonZSL**
This PR fixes the first part of issue #[1031](https://github.com/apache/skywalking/issues/10317), adding a suffix namespace separated by `|`.

Also optimized the makefile target order to let the poetry install work better.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes: <URL to main repo issue>
- [x] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by Superskyyy** [comment]
This is my undergraduate mate doing his first open source contribution. :) Don't scare him off

**Comment by Superskyyy** [comment]
This is to match the behavior of namespace java agent. Welcome to provide feedback on his changes.

**Comment by wu-sheng** [comment]
I will check later today to confirm Java side logic.

**Comment by SheltonZSL** [comment]
Thank you! I will be waiting for your reply.

**Review by kezhenxu94 — APPROVED** [review]
Everything looks perfect from my side, thanks!!

**Review by wu-sheng — APPROVED** [review]
LGTM. Welcome to join the contributor team.

**Comment by SheltonZSL** [comment]
OK，thanks for your reply！

**Pull request merged**
