### PR TITLE
Fix: user/password replacement is not allowed for relative urls

### PR DESCRIPTION
**Pull request by tsonglew**
### Fix user/password replacement is not allowed for relative urls

When using the parameter base_url of [ClientSession](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession) constructor, `with_user` and `with_passwrod` at [here](https://github.com/apache/skywalking-python/blob/28602aec01a7f5434c7fe1bd73338cd4478e0761/skywalking/plugins/sw_aiohttp.py#L43) will raise error. 

sample code 

```python
app = Flask(__name__)


@app.get("/cat")
async def application():
    try:
        await aiohttp_demo()
        return {"Cat Fun Fact": "Fact is cat, cat is fat"}
    except Exception as e: 
        return {"message": str(e)}

async def aiohttp_demo():
    async with aiohttp.ClientSession('http://httpbin.org') as session:
        async with session.get('/get'):
            pass
        async with session.post('/post', data=b'data'):
            pass
        async with session.put('/put', data=b'data'):
            pass
```

Since relative URL is used in `session.get('/get')`,  `_sw_request` receives the relative URL as  argument `str_or_url`, then `URL(str_or_url)` will be a relative URL. But `with_user` and `with `with_password` raises `ValueError` when URL is not absolute.

`with_user` for example:

```python
def with_user(self, user):
        val = self._val
        if user is None:
            password = None
        elif isinstance(user, str):
            user = self._QUOTER(user)
            password = val.password
        else:
            raise TypeError("Invalid user type")

        # ================== HERE ===================
        if not self.is_absolute():
            raise ValueError("user replacement is not allowed for relative URLs")
        # ================== HERE ===================
        return URL(
            self._val._replace(
                netloc=self._make_netloc(user, password, val.hostname, val.port)
            ),
            encoded=True,
        )
```

This PR fix it by replacing the URL with a absolute one.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Why the submodule is changed too?

**Review by kezhenxu94 — COMMENTED** [review]
Please revert the submodule and it looks good to me

**Comment by tsonglew** [comment]
@kezhenxu94 PTAL

**Review by kezhenxu94 — DISMISSED** [review]

**Comment by wu-sheng** [comment]
I think you should fix code stylr things?

**Comment by kezhenxu94** [comment]
@tsonglew can you remove the unused import to fix the linting error?

**Review by wu-sheng — DISMISSED** [review]

**Comment by wu-sheng** [comment]
http plugin tests seem to be broken. Could you fix them?

**Comment by tsonglew** [comment]
sure

**Comment by tsonglew** [comment]
PTAL. Updated the implementation to fullfil URL, since skywalking agent is declared to support aiohttp ^3.7.4, but `ClientSession._build_url` is added in aiohttp v3.8.0. And [actions](https://github.com/tsonglew/skywalking-python/actions/runs/10021981890
) succeded in my fork repo.

**Comment by wu-sheng** [comment]
@kezhenxu94 please recheck.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
