### PR TITLE
Add tables to show agent features and clean up configs

### PR DESCRIPTION
**Pull request by Superskyyy**
As Python agent grows and syncing features with the Java agent, even myself don't remember what was supported especially we have 3 reporter protocols (grpc http kafka) that not all of them support all telemetry data. 

So adding two tables to show it clearly for our users/developers so they can quick start and avoid installing the wrong version.

Preview:
image

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes: <URL to main repo issue>
- [ ] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
I can't find meter and log docs, but the table shows supported.
Are those missed docs?

**Comment by Superskyyy** [comment]
> I can't find meter and log docs, but the table shows supported. Are those missed docs?

The log reporter doc is here, but meter is missing. It's because we didn't add it to the menu.yaml, adding now.
image

**Comment by Superskyyy** [comment]
@wu-sheng Btw, I remember HTTP handler (receiver) on meter is not implemented on the OAP side, is it intentional or just a missed thing not done?

**Comment by wu-sheng** [comment]
It is just never defined from API level, and not implemented.
Feel free to add the API and implement it.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
