### PR TITLE
feat: report metrics related to pvm

### PR DESCRIPTION
**Pull request by jiang1997**
# Metrics
### process_cpu_utilization
cpu utilization of the current process
### thread_active_count
number of threads invoked by the current process and its children
### process_mem_utilization
memory utilization of the current process 
### gc_g0
number of objects of generation 0
### gc_g1
number of objects of generation 1
### gc_g2
number of objects of generation 2
### gc_time

# 
For now, `MeterReportService` is available with gRPC only. So does the e2e test.
I will implement `MeterReportService` and enable e2e test for Kafka later. 

#
Welcome any advice about naming.

### CODE REVIEW

**Comment by Superskyyy** [comment]
Will need to add the E2E testing case to the PR.

**Comment by wu-sheng** [comment]
When using MAL to analysis PVM metrics, a new MAL file should be added and activated in the server side, as well as UI.
So, we need to add one side without e2e, or manually mount one file, and remove later after backend PR accepted.

**Comment by jiang1997** [comment]
> When using MAL to analysis PVM metrics, a new MAL file should be added and activated in the server side, as well as UI. So, we need to add one side without e2e, or manually mount one file, and remove later after backend PR accepted.

Thanks for the suggestion. For now, I manually mount MAL files and will create necessary PR to `Skywalking` backend later.

**Comment by wu-sheng** [comment]
You could refer https://github.com/apache/skywalking/pull/9711 to make backend PR ready.

@easonyipj You could ref this to take a look at agent side testing.

**Comment by easonyipj** [comment]
> You could refer [apache/skywalking#9711](https://github.com/apache/skywalking/pull/9711) to make backend PR ready.
> 
> @easonyipj You could ref this to take a look at agent side testing.

OK, I got it, thanks.

**Comment by jiang1997** [comment]
> 

got it.

**Comment by jiang1997** [comment]
> You could refer [apache/skywalking#9711](https://github.com/apache/skywalking/pull/9711) to make backend PR ready.
> 
> @easonyipj You could ref this to take a look at agent side testing.

got it.

**Comment by Superskyyy** [comment]
Any updates?

**Comment by jiang1997** [comment]
> Any updates?

I plan to implement MeterReportService and enable e2e test for Kafka, but it didn't go very well. Anyway, it's ready for review.

**Comment by Superskyyy** [comment]
> > Any updates?
> 
> I plan to implement `MeterReportService` and enable e2e test for Kafka, but it didn't go very well. Anyway, it's ready for review.

I will reach you out for a discussion on the kafka part. cc: @kezhenxu94 for a review of this PR.

**Comment by Superskyyy** [comment]
Kafka issue is solved, it's about using `MeterDataCollection` instead of using `MeterData`

**Review by kezhenxu94 — APPROVED** [review]
Thanks! LGTM

**Comment by kezhenxu94** [comment]
Next we need to configure the UI dashboard in the main repo

**Comment by jiang1997** [comment]
> Next we need to configure the UI dashboard in the main repo

Get it.

**Pull request merged**
