### PR TITLE
Add Httpx plugin

### PR DESCRIPTION
**Pull request by XinweiLyu**
### <Feature description>
This pull request add support for HTTPX library async/sync request. 
- [x] If adding a new plugin, add a component id in [the main repo](https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/component-libraries.yml)
- [x]  If adding a new plugin, add a logo in [the UI repo](https://github.com/apache/skywalking-booster-ui/tree/main/src/assets/img/technologies)
- [x] I have added the library to `pyproject.toml` (plugin group) by running `poetry add library --group plugins`
- [x] I have rebuilt the `Plugins.md` documentation by running `make doc-gen`

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes: <URL to main repo issue>
- [x] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
> If adding a new plugin, add a component id in [the main repo](https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/component-libraries.yml)

About this, I can't find a pull request on the main repo to register this.

**Comment by wu-sheng** [comment]
> > If adding a new plugin, add a component id in [the main repo](https://github.com/apache/skywalking/blob/master/oap-server/server-starter/src/main/resources/component-libraries.yml)
> 
> About this, I can't find a pull request on the main repo to register this.

Oh, this one, https://github.com/apache/skywalking/pull/10383. You should refer the PR in here or at the other side.

**Comment by Superskyyy** [comment]
Another of my roommate, both will try to join this year's GSOC, so they are getting a feel of open source right now.

**Comment by Superskyyy** [comment]
Code is good, I have confirmed and tested.

**Review by Superskyyy — APPROVED** [review]

**Pull request merged**
