### PR TITLE
Add requests plugin

### PR DESCRIPTION
**Pull request by alonelaval**
add requests plugin

### CODE REVIEW

**Comment by wu-sheng** [comment]
@kezhenxu94 Please add the plugin test tool into this repo.

@alonelaval plugin test in Python will follow the same tool in Java, read this document, https://github.com/apache/skywalking/blob/master/docs/en/guides/Plugin-test.md

**Comment by kezhenxu94** [comment]
@alonelaval thanks for contributing, I'll review this PR by this weekend

**Comment by alonelaval** [comment]
> @alonelaval thanks for contributing, I'll review this PR by this weekend

ok

**Comment by kezhenxu94** [comment]
Hi @alonelaval , I have a quick look at this PR, and it looks generally good to me, can you please take a look at https://github.com/apache/skywalking-python/pull/10 and add the plugin test here too? We should guarantee the plugin works well now and in the future when other contributors modify the codes, thanks :)

**Comment by kezhenxu94** [comment]
Hi @alonelaval , we plan to release the first version of SkyWalking-Python, if you hope this plugin to be included in the first version, please let me know and let's review to make it possible to be included in the first version, thanks :)

**Comment by alonelaval** [comment]
ok, what can i do？

> Hi @alonelaval , we plan to release the first version of SkyWalking-Python, if you hope this plugin to be included in the first version, please let me know and let's review to make it possible to be included in the first version, thanks :)

**Comment by kezhenxu94** [comment]
> ok, what can i do？
> 
> > Hi @alonelaval , we plan to release the first version of SkyWalking-Python, if you hope this plugin to be included in the first version, please let me know and let's review to make it possible to be included in the first version, thanks :)

Add test for this plugin according to #10

**Comment by alonelaval** [comment]
> @alonelaval I've fixed the test for you, although the `refs` verification is missing, it's missed from the first place so I'll add it in another PR, thanks for the plugin :)

thanks。。。My network is sososo bad......docker testCase cann‘t run......

**Pull request merged**
