### PR TITLE
Don't install loguru when not active

### PR DESCRIPTION
**Pull request by ZEALi**
As a log reporter, it should not be activated when user don't want (agent.archive_log will fail). 

maybe sw_loguru should be treated as sw_logging which is installed before other normal plugins in agent.start(),  
or re-factor sw_loguru & sw_logging into a "log reporter" plugins instead of default "trace reporter" plugins?

### CODE REVIEW

**Comment by Superskyyy** [comment]
Please fix lint. 

Regarding your question, I think I would prefer the second design as it is more clear and support future extensions. Would you like to proceed on the refactor?

**Comment by Superskyyy** [comment]
Please remember to add a changelog for this fix.

**Comment by ZEALi** [comment]
> 

Sure. I'll work on the sepreated hook for “log reporter” plugins.

**Comment by Superskyyy** [comment]
Any updates? @ZEALi

**Comment by Superskyyy** [comment]
Closing this in favor of a newer PR including this change https://github.com/apache/skywalking-python/pull/302/files

**Pull request closed without merging**
