### PR TITLE
Add Py3.12 to the test matrix

### PR DESCRIPTION
**Pull request by wu-sheng**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes: <URL to main repo issue>
- [ ] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
@kezhenxu94 It seems python 3.12 failing, same reported from mailing list.

**Comment by hanyuling** [comment]
你好，我想请教一下，skywalking-python 没有实现向子线程中传递traceId吗？我使用了@runnable()，但是子线程中的traceid和调用线程中的不一致。

**Comment by hanyuling** [comment]
Hello, I would like to ask if skywalking-python does not implement passing the traceId to child threads? I used @runnable(), but the traceId in the child thread is not consistent with the one in the calling thread.

**Comment by wu-sheng** [comment]
I think that part is plugin implementation responsibilities.

**Comment by hanyuling** [comment]
> I think that part is plugin implementation responsibilities.

Is there a plug-in that can realize this function now?

**Comment by wu-sheng** [comment]
> > I think that part is plugin implementation responsibilities.
> 
> Is there a plug-in that can realize this function now?

I don't know. And this PR is not a place to discuss this.

**Comment by hanyuling** [comment]
> > > I think that part is plugin implementation responsibilities.
> > 
> > 
> > Is there a plug-in that can realize this function now?
> 
> I don't know. And this PR is not a place to discuss this.

ok, thank you.

**Pull request closed without merging**
