### PR TITLE
Optimize loguru reporter plugin

### PR DESCRIPTION
**Pull request by Jedore**
Optimize the loguru reporter plugin.
- [x] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by Jedore** [comment]
Seems the error is:
```
-         text: '2023-04-24 02:08:51.207 | WARNING  | __main__:application:44 - Loguru -           provider warning reported. 
+         text: Loguru provider warning reported.
```
and
https://github.com/apache/skywalking-python/actions/runs/4781572067/jobs/8500362225?pr=302#step:6:764

I test in my own repo as metioned in https://github.com/apache/skywalking/discussions/10723 after simpling the loguru test https://github.com/Jedore/skywalking-python/blob/ttt/tests/plugin/data/sw_loguru/services/provider.py.

So i think may be the key is skywalking-agent-test-tool syntax `end with` ?

**Comment by Jedore** [comment]
It's my error. I have commited new fix.

**Comment by Superskyyy** [comment]
Thanks for fixing it, great work!

**Comment by Superskyyy** [comment]
The oap container in kafka e2e cases fails and it's not your problem. I'm investigating now.

**Comment by Superskyyy** [comment]
I see the problem, Kraft mode became default in our pulled bitnami kafka image and the configuration isn't enough for it. I will start another PR later today to fix that.

**Review by Superskyyy — APPROVED** [review]

**Comment by Superskyyy** [comment]
LGTM and once the other PR is merged this one can merge.

**Comment by wu-sheng** [comment]
Should be in 1.0.1 or pending?

**Comment by Superskyyy** [comment]
> Should be in 1.0.1 or pending?

This PR also fixes a potential reporter bug introduced in 1.0.0, so it will be included in the 1.0.1 patch. But no further features will be added beyond this pr.

**Comment by wu-sheng** [comment]
CI is still failing.

**Comment by Superskyyy** [comment]
GitHub actions is not working properly https://www.githubstatus.com/ let's wait a bit and see if it passes.

**Comment by Superskyyy** [comment]
> CI is still failing.

GHA runners are not working properly, let's wait a bit and see if it passes. https://www.githubstatus.com/

**Comment by Superskyyy** [comment]
Great, merging.

**Pull request merged**
