### PR TITLE
Use slim in plugin tests

### PR DESCRIPTION
**Pull request by Superskyyy**
Use slim to avoid long artifact build/download time in actions. (image size reduced by half) 

If I understand correctly slim is only different in terms of minimal external-to-python libs and should in no way interfere with plugin tests. (build-essential is additionally installed in image)

Please indicate if there's potential risk in this one.

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes: <URL to main repo issue>
- [x] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by Superskyyy — COMMENTED** [review]
Something is wrong with the tests, investigating please don't merge

**Review by kezhenxu94 — DISMISSED** [review]
LGTM when you mark it ready for review and CI passed 🧐

**Comment by Superskyyy** [comment]
> LGTM when you mark it ready for review and CI passed 🧐

It will likely stuck forever 😂 Just found out there was a missed system-level dependency (for mysql-client) in the image.

**Comment by Superskyyy** [comment]
I also updated compose retries and ci output logic. It will never hang for 30minutes anymore.

**Review by kezhenxu94 — DISMISSED** [review]

**Comment by Superskyyy** [comment]
zzZ my bad again.

**Review by wu-sheng — APPROVED** [review]

**Comment by Superskyyy** [comment]
Finially😔

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
