### PR TITLE
add http ignore by method

### PR DESCRIPTION
**Pull request by tom-pytel**
* Added SW_HTTP_IGNORE_METHOD which will allow ignoring http operations by method (GET, POST, HEAD, OPTIONS, etc...)
* Set default SW_AGENT_MAX_BUFFER_SIZE back to 10000 from 1000, which turns out to be too small for python (many unnecessarily dropped spans).

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]
Will take a look at the sanic case

**Comment by tom-pytel** [comment]
Still failing, do you have access to the logs to see why?

**Comment by kezhenxu94** [comment]
sanic test case seems to always fail in Python 3.8, need to check why

**Comment by tom-pytel** [comment]
> sanic test case seems to always fail in Python 3.8, need to check why

I did a basic check on my side with python 3.8.11 and sanic 20.3.0 and it works.

**Comment by kezhenxu94** [comment]
Didn't reproduce locally or in another branch https://github.com/apache/skywalking-python/runs/3252404801

**Comment by tom-pytel** [comment]
20.3.0 worked this time, what did you change?

**Comment by tom-pytel** [comment]
Seems to be stuck on starting CheckStatus test...

**Comment by kezhenxu94** [comment]
> 20.3.0 worked this time, what did you change?

Didn't change anything, it seems to be unstable, not constantly fail.

**Comment by kezhenxu94** [comment]
> Seems to be stuck on starting CheckStatus test...

This is GitHub action issue, maybe the job is bot scheduled.

**Comment by kezhenxu94** [comment]
Ok. GitHub actions is degraded. Let's merge this anyway.

**Comment by tom-pytel** [comment]
> Ok. GitHub actions is degraded. Let's merge this anyway.

Tried to merge locally and push to github master but no luck:
```
tom@tom-VirtualBox:~/src/revdebugpy/skywalking-python {master} $ git push upstream
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "CheckStatus" is cancelled.
To github.com:apache/skywalking-python.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:apache/skywalking-python.git'
```

**Comment by tom-pytel** [comment]
This time sanic 20.3.0 failed for py 3.9...

**Comment by tom-pytel** [comment]
Disabled sanic 20.3.0 test for now.

**Review by kezhenxu94 — APPROVED** [review]

**Pull request merged**
