### PR TITLE
Fix unexpected 'decode' AttributeError when MySQLdb module is mapped by PyMySQL

### PR DESCRIPTION
**Pull request by ZEALi**
In some use cases, `pymysql.install_as_MySQLdb()` will be used to initialize a 'fake' MySQLdb module, which is actually mapped to pymysql module.

Unfortunately, sw_mysqlclient plugin changes the data type of `connection.db` from `bytes` into `str`,  which is regard as `bytes` in sw_pymysql plugin. That will cause the `AttributeError: 'str' object has no attribute 'decode'` exception in sw_pymysql.py line 45.

So if the `MySQLdb` module  is only a pointer to `pymysql`, we should just raise ImportError instead of installation for sw_mysqlclient plugin.

- [x] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please fix CI.

**Comment by wu-sheng** [comment]
And you should follow PR template to `Update the CHANGELOG.md.`

**Comment by wu-sheng** [comment]
@kezhenxu94 Please take a look. We also have some CIs fail, but should be irrelevant. We may need some fixes first.

**Comment by Superskyyy** [comment]
Ok I will take a look thanks

**Comment by Superskyyy** [comment]
I will temporariy disable the uwsgi case, I believe that uwsgi is getting less attraction and support will be dropped sooner or later.

**Comment by Superskyyy** [comment]
LGTM, let's wait for CI.

**Comment by Superskyyy** [comment]
Gonna kick off a release soon this weekend.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
