### PR TITLE
Fix tornado socket == None

### PR DESCRIPTION
**Pull request by tom-pytel**
Sometimes `socket` here is none, like when processing happens after connection has been closed.

### CODE REVIEW

**Comment by tom-pytel** [comment]
Umm ... old links or temporarily down?

**Comment by tom-pytel** [comment]
Can't merge due to dead link checker failed, and running it again doesn't fix.

**Comment by wu-sheng** [comment]
This seems a GitHub issue?

**Comment by tom-pytel** [comment]
> This seems a GitHub issue?

Any way to force merge?

**Comment by wu-sheng** [comment]
When I clicked the file from https://github.com/apache/skywalking-python/tree/master/tests/plugin/http/sw_http, it works. Then refresh failure.

**Comment by tom-pytel** [comment]
Now it let me merge, weird.

**Pull request merged**
