### PR TITLE
Change from pkg_resources to importlib metadata

### PR DESCRIPTION
**Pull request by shenxiangzhuang**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue url. Closes: https://github.com/apache/skywalking/issues/11509
- [x] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by kezhenxu94 — APPROVED** [review]
@shenxiangzhuang thanks. Can you fix the linting issue and make the tests passed?

**Comment by shenxiangzhuang** [comment]
@kezhenxu94 Ok, I'll try to fix it

**Comment by shenxiangzhuang** [comment]
After fix the linting error the CI run almost success with 2 fail jobs related to "[Plugin and Unit Tests (3.10, tests/unit)](https://github.com/apache/skywalking-python/actions/runs/6785690672/job/18445306626#logs)". I'm not sure why it failed and I don't find the [Re-running failed jobs](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#re-running-failed-jobs-in-a-workflow) button, so I improved the changelog to trigger the re-running of CI.

**Comment by Superskyyy** [comment]
Thank you for the contribution! The reason why rerun doesn't work is probably due to the github limitation for first time contributors at this repo.

**Comment by Superskyyy** [comment]
> After fix the linting error the CI run almost success with 2 fail jobs related to "[Plugin and Unit Tests (3.10, tests/unit)](https://github.com/apache/skywalking-python/actions/runs/6785690672/job/18445306626#logs)". I'm not sure why it failed and I don't find the [Re-running failed jobs](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#re-running-failed-jobs-in-a-workflow) button, so I improved the changelog to trigger the re-running of CI.

There are some flaky runs due to uwsgi being unstable, I will attend to that in a separate pr by increasing the e2e retry intervals.

**Review by Superskyyy — APPROVED** [review]
LGTM. Thanks a lot.

**Pull request merged**
