### PR TITLE
Refactor current Python agent docs to serve on SkyWalking official website

### PR DESCRIPTION
**Pull request by Superskyyy**
Refactored and moved the existing docs into a more organized format suitable for SkyWalking Website to ingest and host.

Part of - https://github.com/apache/skywalking/issues/7687

Visit my github.io deployment of the new docs -> https://superskyyy.github.io/docs/skywalking-python/latest/readme/

- [x] Refactor Python repo docs
- [ ] Add new entry to website repo - TODO
- [ ] Refactor Python repo main README - TODO

This PR deals with the first step ↑. 

Once this one merges, I will PR to deploy the docs officially on the https://skywalking.apache.org/ website, finally update our main README to reflect the new documentation URL, and remove the lines belonging to the actual doc.

### CODE REVIEW

**Review by wu-sheng — COMMENTED** [review]
Does the last todo mean, readme doc will be removed later, and link to website doc? If so, I am good.

**Comment by Superskyyy** [comment]
> Does the last todo mean, readme doc will be removed later, and link to website doc? If so, I am good.

Yes,exactly.

**Review by wu-sheng — APPROVED** [review]
Good to me. Wait for @kezhenxu94 to check doc details.

**Review by kezhenxu94 — APPROVED** [review]
Thank you @Superskyyy very much

**Comment by Superskyyy** [comment]
We might also need a doc for the profiling feature?

**Comment by kezhenxu94** [comment]
> We might also need a doc for the profiling feature?

After we release 0.7.0, @Humbertzhang will submit one for this

**Comment by wu-sheng** [comment]
We have a blog draft for it actually.

**Pull request merged**
