### PR TITLE
Bump up the version to 0.4.0

### PR DESCRIPTION
**Pull request by kezhenxu94**
Forgot to update the version number before voting 😢 @wu-sheng do we need another round voting? I hope no

Can I update this version number (and re-tag) and upload to Pypi? (Can't upload without updating the version)

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
I am afraid you have to re-vote the release, as you changed the commit id sadly.

**Comment by wu-sheng** [comment]
I am assuming this file is in the release tar ball, right?

**Comment by kezhenxu94** [comment]
> I am assuming this file is in the release tar ball, right?

Yes it is

**Comment by wu-sheng** [comment]
Then we need another release vote.

**Pull request merged**
