### PR TITLE
Make plugin compatible with Django < 2.2

### PR DESCRIPTION
**Pull request by Humbertzhang**

### CODE REVIEW

**Comment by shuguang-dong** [comment]
I just tried Djano==3.1 and apache-skywalking==0.2.0,when I use cmd "python3 test_django.py runserver 0.0.0.0:9090",only use http protocol can work well,grpc protocol can't work.
But I have another question: 
I only request such as start with 'http://0.0.0.0:9000/uri' agent is work well. But my django server is run with 0.0.0.0:8000.I request my django server ,agent still now work.I think agent server and my django server is uncommitted, Am i wrong?

**Comment by shuguang-dong** [comment]
I also try set agent code in settings.py,but when I start my django server ,it will throw exception: raise RuntimeError('the agent can only be started once'). So, I want use agent to listen my django server,what should I do? thank you very much!

**Comment by kezhenxu94** [comment]
@shuguang-dong please provide a demo project to help us reproduce, you have so many different ports in the comment, `9090`, `8000`, `9000`, I'm wondering whether you mess things up locally, anyway, please provide a reproducible demo project

**Comment by Humbertzhang** [comment]
The agent can only be started once, you  just need to find a place, import skywalking and use  `agent.start()` to start it. i think maybe you use `agent.start()`  twice when you run your app.

```Python
from skywalking import agent, config
config.service_name = "test"
config.logging_level = "DEBUG"
agent.start()
```

**Comment by shuguang-dong** [comment]
Hold on pelase.I provide my demo project after

**Comment by shuguang-dong** [comment]
Hello, here is my demo project: https://github.com/shuguang-dong/demo
I use cmd: python3 agent.py runserver 0.0.0.0:9090
after I visit url: http://0.0.0.0:9090/index ,agent work well(on protocol='http')
but I run my django server ,it listen 8000 port, I visit url http://127.0.0.1:8000/ , the agent not trace this request

**Comment by kezhenxu94** [comment]
@shuguang-dong thanks for providing the demo, we'll take a look soon

**Comment by Humbertzhang** [comment]
when you run `python3 agent.py runserver 0.0.0.0:9090`, it just start a django server with skywalking. 
There's no need for you to run another django app.

**Comment by shuguang-dong** [comment]
But my backend server is run with 8000，how can I use agent to listen 8000 prot?

**Pull request merged**
