### PR TITLE
Fix configuration names

### PR DESCRIPTION
**Pull request by SheltonZSL**
Via suggestion from (https://github.com/Superskyyy)#273, I changed the config file.

- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue URL. #273
- [x] Update the [`CHANGELOG.md`](https://github.com/apache/skywalking-python/blob/master/CHANGELOG.md).

### CODE REVIEW

**Comment by Superskyyy** [comment]
We sat side by side to make this one, I will take another look in a bit.

**Comment by wu-sheng** [comment]
> We sat side by side to make this one, I will take another look in a bit.

Ah, you mean really physical `side by side`? :) Interesting peer review work.

**Comment by Superskyyy** [comment]
> > We sat side by side to make this one, I will take another look in a bit.
> 
> Ah, you mean really physical `side by side`? :) Interesting peer review work.

Yes, literally sitting in one room, two of my roommates are now trying to contribute more and participate in this year's GSOC. @SheltonZSL @XinweiLyu

**Comment by Superskyyy** [comment]
@SheltonZSL  Please resolve the conflict by accepting all changes in the master branch? Tony's pr added dependency so this file has to be his version.

**Comment by SheltonZSL** [comment]
Ok, thank you for reminding me. I have resolved the conflict.

**Review by Superskyyy — APPROVED** [review]
LGTM

**Pull request merged**
